### ISSUE TITLE
나이를 생년월일로 변경

### ISSUE THREAD

**Issue by LeeSM0518** [seungbin-kim/hierarchical-board-api#1]
https://github.com/seungbin-kim/hierarchical-board-api/blob/6775f0d2ec8d1804f83c4e9f2aeea471207de456/src/main/java/com/personal/board/entity/User.java#L45

나이로 값을 DB에 저장해놓으면 매년 값을 업데이트 해줘야하기 때문에 보통 생년월일로 저장합니다.

**Comment by seungbin-kim** [comment]
감사합니다. 생년월일을 사용하도록 반영하도록 하겠습니다.

> https://github.com/seungbin-kim/hierarchical-board-api/blob/6775f0d2ec8d1804f83c4e9f2aeea471207de456/src/main/java/com/personal/board/entity/User.java#L45
> 
> 나이로 값을 DB에 저장해놓으면 매년 값을 업데이트 해줘야하기 때문에 보통 생년월일로 저장합니다.

**Comment by seungbin-kim** [comment]
> https://github.com/seungbin-kim/hierarchical-board-api/blob/6775f0d2ec8d1804f83c4e9f2aeea471207de456/src/main/java/com/personal/board/entity/User.java#L45
> 
> 나이로 값을 DB에 저장해놓으면 매년 값을 업데이트 해줘야하기 때문에 보통 생년월일로 저장합니다.

**Comment by seungbin-kim** [comment]
> https://github.com/seungbin-kim/hierarchical-board-api/blob/6775f0d2ec8d1804f83c4e9f2aeea471207de456/src/main/java/com/personal/board/entity/User.java#L45
> 
> 나이로 값을 DB에 저장해놓으면 매년 값을 업데이트 해줘야하기 때문에 보통 생년월일로 저장합니다.

감사합니다. 나이부분은 생년월일을 사용하도록 수정하겠습니다.
