### ISSUE TITLE
409 에러 적용

### ISSUE THREAD

**Issue by LeeSM0518** [seungbin-kim/hierarchical-board-api#5]
예외 처리할 때, 이메일 중복이나 닉네임 중복도 모두 400 에러 코드를 적용했는데 이런 비즈니스 로직 상 불가능한 경우에는 보통 409 에러를 응답합니다.
400 에러를 응답했던 경우 중에 409 에러가 적용되면 좋을 부분들을 변경해주세요.

![image](https://user-images.githubusercontent.com/43431081/110903251-7e9d7900-834a-11eb-9d7a-eca8110d13f9.png)

**Comment by seungbin-kim** [comment]
> 예외 처리할 때, 이메일 중복이나 닉네임 중복도 모두 400 에러 코드를 적용했는데 이런 비즈니스 로직 상 불가능한 경우에는 보통 409 에러를 응답합니다.
> 400 에러를 응답했던 경우 중에 409 에러가 적용되면 좋을 부분들을 변경해주세요.
> 
> ![image](https://user-images.githubusercontent.com/43431081/110903251-7e9d7900-834a-11eb-9d7a-eca8110d13f9.png)

바로 반영 해 보겠습니다. 감사합니다.
